# MySQL. Versions 5.1.10 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: tickets_development

test:
  <<: *default
  database: tickets_test

production:
  <<: *default
  database: <%= ENV['TICKETS_DATABASE'] %>
  username: <%= ENV['TICKETS_DATABASE_USERNAME'] %>
  password: <%= ENV['TICKETS_DATABASE_PASSWORD'] %>
